### ISSUE TITLE
java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String 

### ISSUE THREAD

**Issue by Mimetis** [Azure-Samples/cdm-azure-data-services-integration#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
I make a cross post here, from the repository https://github.com/Azure/spark-cdm

See issue https://github.com/Azure/spark-cdm/issues/3

The issue is related to the new **2.4 spark-cdm** branch, allowing to use spark 2.4
It seems we still have an issue when calling function like `display(foo)`:

```
java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getUTF8String(rows.scala:46)

```

**Comment by shamv** [comment]
Facing the same issue...Please share latest spark-cdm-assembly-0.3.jar file to address this.

**Comment by shamv** [comment]
![image](https://user-images.githubusercontent.com/9548391/63419604-b3c83a80-c437-11e9-9c75-6e31905201d5.png)
![image](https://user-images.githubusercontent.com/9548391/63419649-c3478380-c437-11e9-8b42-fb228ab9c0c5.png)


java.lang.String cannot be cast to org.apache.spark.unsafe.types.UTF8String
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getUTF8String(rows.scala:46)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getUTF8String(rows.scala:195)
